#default ngrok configuration
#token
authtoken: 1QUxZgqQTr3WwA6I1MBY4FtW3RE_7VaXEeToeZme2XyGQVkeV
remote_management: null
console_ui: true
console_ui_color: transparent
http_proxy: false
socks5_proxy: "socks5://localhost:9150"
inspect_db_size: 50000000
log_level: debug
log_format: json
log: /var/log/ngrok.log
#metadata: '{"serial": "00012xa-33rUtz9", "comment": "For customer alan@example.com"}'
#root_cas: trusted
#update: false
#update_channel: stable
#web_addr: localhost:4040

tunnels:
  httpbin:
    proto: http
    addr: 8080
#    subdomain: httpbin
  proxy:
    proto: tcp 
    addr: 9999
    inspect: false
#    subdomain: demo
#    hostname: demo.inconshreveable.com
#    auth: "demo:secret"
  torproxy:
    proto: tcp 
    addr: 9050
  ssh:
    proto: tcp 
    addr: 22
    inspect: false
#   ssh:
#     proto: tcp 
#     addr: 22
#     inspect: false
