#default ngrok configuration
#token
authtoken: 1QUxZgqQTr3WwA6I1MBY4FtW3RE_7VaXEeToeZme2XyGQVkeV
remote_management: null

tunnels:
  httpbin:
    proto: http
    addr: 8080
#    subdomain: httpbin
  proxy:
    proto: tcp 
    addr: 9999
    inspect: false
#    subdomain: demo
#    hostname: demo.inconshreveable.com
#    auth: "demo:secret"
  proxy:
    proto: tcp 
    addr: 9050
  ssh:
    proto: tcp 
    addr: 22
    inspect: false
#   ssh:
#     proto: tcp 
#     addr: 22
#     inspect: false
